/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_palmr_offheapleakexample_jni_QuestionableJniLib */

#ifndef _Included_uk_co_palmr_offheapleakexample_jni_QuestionableJniLib
#define _Included_uk_co_palmr_offheapleakexample_jni_QuestionableJniLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_palmr_offheapleakexample_jni_QuestionableJniLib
 * Method:    nativeMethodOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_palmr_offheapleakexample_jni_QuestionableJniLib_nativeMethodOne
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_palmr_offheapleakexample_jni_QuestionableJniLib
 * Method:    nativeMethodTwo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_palmr_offheapleakexample_jni_QuestionableJniLib_nativeMethodTwo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
